# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6234d5b60a14f850c81230415a124ff6d04f94187f6a7af82cb7c6b58ddf9afe3fed2deeb97537780c7683bb68057ca23a782076e7ad43ebde0a7ef4a7e108

test:
  secret_key_base: 4664bef2a7c105dc36d6a942a1c8c71dbf4195b524f8367da66a88ffec6a2b38edf7c1421af739753f980fa994f89b322ba993f50560436568f5fd6400883567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
